
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

sensor:
  - platform: nws_alerts
    zone_id: 'MAZ015'
  - platform: mqtt
    state_topic: "soil/pothos/"
    unit_of_measurement: "%"
    name: pothos
  - platform: mqtt
    state_topic: "soil/yucca/"
    unit_of_measurement: "%"
    name: yucca
  - platform: template
    sensors:
      brightness:
        friendly_name: "Brightness"
        value_template: '{{ states.light.living_room_fan_light.attributes.brightness }}'
      hvac_fan:
        friendly_name: HVAC fan
        value_template: '{{ states.climate.living_room.attributes.fan }}'
      half_bath_fan:
        friendly_name: Half Bath fan
        value_template: '{{ states.switch.half_bath_fan.state }}'
      kitchen_cam_motion:
        friendly_name: Kitchen Cam motion
        value_template: '{{states.sensor.camera_1_motion.state | int }}'
        unit_of_measurement: au
      living_room_cam_motion:
        friendly_name: Living Room Cam motion
        value_template: '{{ states.sensor.camera_2_motion.state | int }}'
        unit_of_measurement: au
      higgins_last_run:
        friendly_name: Time since last run
        value_template: '{{ now() - state_attr("automation.request_cleaning_when_not_home","last_triggered") }}'
  - platform: mbta_predictions
    predictions:
    - depart_from: Downtown Crossing
      arrive_at: Jackson Square
      route: Orange Line  #Subway
    - depart_from: Stony Brook
      arrive_at: Ruggles
      route: Orange Line  #Subway
    - depart_from: Haymarket
      arrive_at: Ruggles
      route: Orange Line  #Subway
    - depart_from: Columbus Ave @ Walnut Ave
      arrive_at: Ruggles
      route: Ashmont Station - Ruggles Station via Talbot Ave  # Route 22

recorder:
  purge_keep_days: 10
  db_url: !secret URL_MariaDB_Thing
  
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: home_assistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  exclude:
    domains:
      - automation
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature
    sensor.*battery_level:
      override_measurement: battery

binary_sensor:
  - platform: workday
    country: US
  - platform: generic_hygrostat
    name: Bathroom Hygrostat
    sensor: sensor.zooz_zse40_4_in_1_sensor_relative_humidity
    delta_trigger: 5 # Optional humidity swing to detect
    target_offset: 3 # Optional dehumidification target offset
    max_on_time: 3600 # Optional # Optional safety max on time
  - platform: template
    sensors:
      bin_kitchen_cam_motion:
        friendly_name: Kitchen Cam motion
        value_template: '{{states.sensor.kitchen_cam_motion.state | int > 400}}'
        device_class: motion
      bin_living_room_cam_motion:
        friendly_name: Living Room Cam motion
        value_template: '{{states.sensor.living_room_cam_motion.state | int > 400}}'
        device_class: motion
      door_1_sensor:
        friendly_name: Door #1
        value_template: '{{states.sensor.aeotec_limited_unknown_type_0102_id_00bb_access_control.state | int == 22 }}'
        device_class: door
     
input_boolean:
  set_vacation:
    name: Toggle thermostat automations
    icon: mdi:airplane-takeoff
    initial: off
  resume_thermostat:
      name: Resume thermostat schedule
      icon: mdi:thermostat
      initial: off
  resume_fan_scene:
      name: Resume Fan Scene
      icon: mdi:fan
      initial: off

# switch:
#  - platform: command_line
#    switches:
#      camera_1:
#        command_on: 'curl -k "http://192.168.115.201:7999/1/detection/start"'
#        command_off: 'curl -k "http://192.168.115.201:7999/1/detection/pause"'
#        command_state: 'curl -s "http://192.168.115.201:7999/1/detection/status"'
#        value_template: '{{ "ACTIVE" in value }}'
#        friendly_name: Motion Sensor Camera – Kitchen
#      camera_2:
#        command_on: 'curl -k "http://192.168.115.201:7999/2/detection/start"'
#        command_off: 'curl -k "http://192.168.115.201:7999/2/detection/pause"'
#        command_state: 'curl -s "http://192.168.115.201:7999/2/detection/status"'
#        value_template: '{{ "ACTIVE" in value }}'
#        friendly_name: Motion Sensor Camera – Living Room

android_ip_webcam:
  - host: 192.168.115.226
    name: Camera 1
    username: ha
    password: !secret webcam_password
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - motion_detect
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
  - host: 192.168.115.144
    name: Camera 2
    username: ha
    password: !secret webcam_password
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - motion_detect
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
      
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.115.2-255
    track_new_devices: yes
    interval_seconds: 60
    consider_home: 300
  - platform: google_maps
    username: !secret google_email
    max_gps_accuracy: 100

timer:
  circulate:
    duration: '01:30:00'
  higgins_timer:
    duration: '00:45:00'
    
tts:
  - platform: google_translate

notify:
  - name: eric
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: emilliman4@gmail.com
    encryption: starttls
    username: emilliman4@gmail.com
    password: !secret google_otp
    recipient:
      - 2314632031@txt.att.net
      - 7168030273@txt.att.net
    sender_name: Home assistant

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  customize: !include customize.yaml
  time_zone: America/New_York
  media_dirs:
    media: /media
    recordings: /share/motioneye
    
#lovelace:
#  mode: yaml
#  resources:
#    - url: /local/custom-lovelace/mbta_card/mbta-card.js
#      type: module
#    - url: /local/custom-lovelace/weather-card/weather-card.js
#      type: module
#    - url: /local/community/lovelace-layout-card/layout-card.js
#      type: module
#    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js?v=0.9.4
#      type: module